Added Function which returns shared ptr to IOThreadPoolExecutor to the application
facebook/proxygen pull request #230
Opened 2018-05-17 13:33 UTC by badarihp

Hi,
Added getIOThreadPoolExecutor in HTTPServer so that application get access to IOThreadPoolExecutor, which helps in added observers, fetching thread pool stats etc:

Incorporated review comments from : https://github.com/facebook/proxygen/pull/228

regards
 badari

2018-05-17 13:38 UTC, badarihp commented
Hi ,
     Intent is to expose IOThreadPoolExecutor to application so that
1) Application can have access to stats of thread pools
2) Application can add its own observer and 
3) Increase or Decrease  num of processing threads in IOThreadPoolExecutor at runtime.

POC git commit id : 

commit 8b7bfbd66aef9f47cf8d9ae3937070fb4bac7fc9
Author: Badari <badari.hp@gmail.com>
Date:   Thu May 17 19:01:32 2018 +0530

    For testing only, to test if num thread can increase and decrease POC


This need not be merged to main line proxygen. I could not add test code so modified EchoServer as required.

Thanks
 badari

2023-02-23 17:31 UTC, afrind requested changes
Welp this was in my review queue for 4.5 years.  I'm really sorry about that.  The core changes to HTTPServer seem ok but the echo sample changes are strange.  Since I expect this isn't urgent I'm going to close the pull for now.  But we can reopen it if you want to drive it forward.

2023-02-23 17:31 UTC, afrind commented on proxygen/httpserver/samples/echo/EchoServer.cpp
> +    iotpe_->setNumThreads(numThreads.load());
This seems quite strange -- to increase the number of available threads on every request, with no bound?

2023-02-23 17:31 UTC, afrind commented on proxygen/httpserver/samples/echo/EchoServer.cpp
> +std::atomic<int> numThreads;
Making these global is not really ideal - would prefer they be part of something else.

2023-02-23 17:31 UTC, afrind commented on proxygen/httpserver/samples/echo/EchoServer.cpp
> +  explicit IOCallbacks(std::shared_ptr<HTTPServerOptions> options) : options_(options) {}
options isn't used in this class.

2023-02-23 17:31 UTC, closed without merging

2023-03-02 04:43 UTC, badarihp commented
Hey Thanks Alan for response. Ill check out these comments and revert back.